//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZFrameWin.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.WCFServices")]
    public interface WCFServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFServices/GetListUsers", ReplyAction="urn:WCFServices/GetListUsersResponse")]
        System.IO.Stream GetListUsers(string LoginName, string LoginPWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFServices/GetListUsers", ReplyAction="urn:WCFServices/GetListUsersResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetListUsersAsync(string LoginName, string LoginPWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFServices/GetServerDateTime", ReplyAction="urn:WCFServices/GetServerDateTimeResponse")]
        System.IO.Stream GetServerDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFServices/GetServerDateTime", ReplyAction="urn:WCFServices/GetServerDateTimeResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetServerDateTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFServices/Login_UserCheck", ReplyAction="urn:WCFServices/Login_UserCheckResponse")]
        System.IO.Stream Login_UserCheck(string PostValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFServices/Login_UserCheck", ReplyAction="urn:WCFServices/Login_UserCheckResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> Login_UserCheckAsync(string PostValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFServicesChannel : ZFrameWin.ServiceReference1.WCFServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServicesClient : System.ServiceModel.ClientBase<ZFrameWin.ServiceReference1.WCFServices>, ZFrameWin.ServiceReference1.WCFServices {
        
        public WCFServicesClient() {
        }
        
        public WCFServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetListUsers(string LoginName, string LoginPWD) {
            return base.Channel.GetListUsers(LoginName, LoginPWD);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetListUsersAsync(string LoginName, string LoginPWD) {
            return base.Channel.GetListUsersAsync(LoginName, LoginPWD);
        }
        
        public System.IO.Stream GetServerDateTime() {
            return base.Channel.GetServerDateTime();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetServerDateTimeAsync() {
            return base.Channel.GetServerDateTimeAsync();
        }
        
        public System.IO.Stream Login_UserCheck(string PostValue) {
            return base.Channel.Login_UserCheck(PostValue);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> Login_UserCheckAsync(string PostValue) {
            return base.Channel.Login_UserCheckAsync(PostValue);
        }
    }
}
